import type { Claim } from '../../game/domain';

export const claims: Claim[] = [
  { id: 'claim-ambush-north', text: '伏击痕迹集中在北桥附近', sourceDocumentId: 'report-ambush', provenance: { kind: 'investigation', sourceId: 'investigate-ambush-site' }, tags: ['supports', 'source'] },
  { id: 'claim-no-full-order', text: '完整封存命令未遗失且无人单独接触全件', sourceDocumentId: 'report-ambush', provenance: { kind: 'investigation', sourceId: 'investigate-ambush-site' }, tags: ['refutes'] },
  { id: 'claim-shuoyuan-received', text: '敌军行动同时对应北桥与寅时', sourceDocumentId: 'report-ambush', provenance: { kind: 'document', sourceId: 'report-ambush' }, tags: ['enemyConclusion'] },
  { id: 'claim-lu-no-time', text: '陆淳只掌握盖印权限，不知道最终出发时辰', sourceDocumentId: 'ledger-original', provenance: { kind: 'interrogation', sourceId: 'interrogate-lu-ledger' }, tags: ['refutes'] },
  { id: 'claim-lu-seal-order', text: '陆淳掌握驿传盖印与调度顺序', sourceDocumentId: 'ledger-original', provenance: { kind: 'document', sourceId: 'ledger-original' }, tags: ['actor'] },
  { id: 'claim-lu-ledger-change', text: '两版粮册证明陆淳修改过粮袋数量', sourceDocumentId: 'ledger-revised', provenance: { kind: 'document', sourceId: 'ledger-revised' }, tags: ['supports', 'refutes'] },
  { id: 'claim-lu-relief-motive', text: '陆淳改册是为挪出少量军粮救济村民，并非向外传递军情', sourceDocumentId: 'statement-lu', provenance: { kind: 'interrogation', sourceId: 'interrogate-lu-ledger' }, tags: ['supports'] },
  { id: 'claim-zheng-repair-change', text: '笔迹与前后记录证明郑禾修改过车辆损坏数量', sourceDocumentId: 'repair-wagons', provenance: { kind: 'document', sourceId: 'repair-wagons' }, tags: ['supports', 'refutes'] },
  { id: 'claim-zheng-no-route', text: '郑禾只掌握车辆规模，不知道最终路线', sourceDocumentId: 'repair-wagons', provenance: { kind: 'interrogation', sourceId: 'interrogate-zheng-repair' }, tags: ['refutes'] },
  { id: 'claim-zheng-scale', text: '郑禾掌握登记车辆规模', sourceDocumentId: 'repair-wagons', provenance: { kind: 'document', sourceId: 'repair-wagons' }, tags: ['actor'] },
  { id: 'claim-bridge-open', text: '试压记录确认北桥可以通行重型粮车', sourceDocumentId: 'repair-north-bridge', provenance: { kind: 'investigation', sourceId: 'investigate-north-bridge' }, tags: ['supports'] },
  { id: 'claim-du-wheel-question', text: '复查出入记录确认杜衡询问过新车轮规格', sourceDocumentId: 'station-entry', provenance: { kind: 'investigation', sourceId: 'investigate-deep-du' }, tags: ['supports'] },
  { id: 'claim-du-fodder-pattern', text: '常例每辆重车五束草料，此次一百二十束对应二十四辆重车', sourceDocumentId: 'station-entry', provenance: { kind: 'investigation', sourceId: 'investigate-du-records' }, tags: ['supports'] },
  { id: 'claim-lu-denial', text: '陆淳否认或回避修改粮册数量', sourceDocumentId: 'statement-lu', provenance: { kind: 'document', sourceId: 'statement-lu' }, tags: [] },
  { id: 'claim-zheng-denial', text: '郑禾否认改写车辆维修记录', sourceDocumentId: 'statement-zheng', provenance: { kind: 'document', sourceId: 'statement-zheng' }, tags: [] },
  { id: 'claim-zhao-denial', text: '赵简声称不知道集合时辰', sourceDocumentId: 'statement-zhao', provenance: { kind: 'document', sourceId: 'statement-zhao' }, tags: [] },
  { id: 'claim-zhao-copied-order', text: '笔迹核对确认集合命令由赵简亲笔抄写', sourceDocumentId: 'statement-zhao', provenance: { kind: 'investigation', sourceId: 'investigate-handwriting' }, tags: ['refutes', 'actor', 'supports'] },
  { id: 'claim-zhao-time', text: '赵简在审讯突破后承认接触并泄露出发时辰', sourceDocumentId: 'statement-zhao', provenance: { kind: 'interrogation', sourceId: 'interrogate-zhao-time' }, tags: ['actor'] },
  { id: 'claim-zhao-coerced', text: '家属查访确认赵简家人受到袁军控制', sourceDocumentId: 'statement-zhao', provenance: { kind: 'investigation', sourceId: 'investigate-zhao-family' }, tags: ['supports'] },
  { id: 'claim-zhao-night-duty', text: '值簿显示赵简接触值夜安排', sourceDocumentId: 'statement-zhao', provenance: { kind: 'document', sourceId: 'statement-zhao' }, tags: ['actor'] },
  { id: 'claim-du-denial', text: '杜衡声称只按订单送货且不懂军务', sourceDocumentId: 'statement-du', provenance: { kind: 'document', sourceId: 'statement-du' }, tags: [] },
  { id: 'claim-du-route', text: '杜衡承认结合草料、车轮、桥梁和商路迹象判断北桥路线', sourceDocumentId: 'station-entry', provenance: { kind: 'interrogation', sourceId: 'interrogate-du-cipher' }, tags: ['method'] },
  { id: 'claim-price-cipher', text: '异常价格与地支序号构成传递路线和时辰的暗号', sourceDocumentId: 'trade-prices', provenance: { kind: 'investigation', sourceId: 'investigate-du-records' }, tags: ['method', 'refutes', 'supports'] },
  { id: 'claim-south-ford-open', text: '南渡可供普通粮车通行', sourceDocumentId: 'route-map', provenance: { kind: 'document', sourceId: 'route-map' }, tags: ['supports'] },
  { id: 'claim-west-ridge-light', text: '西岭只适合轻车与空车', sourceDocumentId: 'route-map', provenance: { kind: 'document', sourceId: 'route-map' }, tags: ['supports'] },
];
