import type { GameContent } from './domain';

export const minimalContent: GameContent = {
  id: 'guandu',
  characters: [
    { id: 'lu', name: '陆淳', role: '邮驿主吏', access: [], secret: '', responsibility: '' },
    { id: 'zheng', name: '郑禾', role: '军粮书佐', access: [], secret: '', responsibility: '' },
    { id: 'zhao', name: '赵简', role: '书吏', access: ['departureTime'], secret: '', responsibility: '' },
    { id: 'du', name: '杜衡', role: '商人', access: ['routeSignals'], secret: '', responsibility: '' },
  ],
  documents: [
    {
      id: 'doc-zhao',
      title: '集合命令',
      category: 'statement',
      body: '测试文书',
      claimIds: ['claim-zhao-time', 'claim-zhao-denial', 'claim-zhao-copied-order', 'claim-zhao-coerced'],
    },
    {
      id: 'doc-du',
      title: '采购记录',
      category: 'trade',
      body: '测试文书',
      claimIds: ['claim-du-route', 'claim-bridge-open', 'claim-price-cipher', 'claim-shuoyuan-received', 'claim-lu-ledger-change'],
    },
  ],
  claims: [
    { id: 'claim-zhao-time', text: '赵简接触时辰', sourceDocumentId: 'doc-zhao', provenance: { kind: 'interrogation', sourceId: 'interrogate-zhao-time' }, tags: ['actor'] },
    { id: 'claim-zhao-denial', text: '赵简否认知情', sourceDocumentId: 'doc-zhao', provenance: { kind: 'document', sourceId: 'doc-zhao' }, tags: ['statement'] },
    { id: 'claim-zhao-copied-order', text: '赵简誊抄命令', sourceDocumentId: 'doc-zhao', provenance: { kind: 'document', sourceId: 'doc-zhao' }, tags: ['refutes', 'actor'] },
    { id: 'claim-du-route', text: '杜衡可推断路线', sourceDocumentId: 'doc-du', provenance: { kind: 'document', sourceId: 'doc-du' }, tags: ['method'] },
    { id: 'claim-bridge-open', text: '北桥可通重车', sourceDocumentId: 'doc-du', provenance: { kind: 'document', sourceId: 'doc-du' }, tags: ['supports'] },
    { id: 'claim-price-cipher', text: '价格表是暗号', sourceDocumentId: 'doc-du', provenance: { kind: 'document', sourceId: 'doc-du' }, tags: ['method'] },
    { id: 'claim-shuoyuan-received', text: '袁军同时命中路线与时辰', sourceDocumentId: 'doc-du', provenance: { kind: 'document', sourceId: 'doc-du' }, tags: ['enemyConclusion'] },
    { id: 'claim-zhao-coerced', text: '赵简家人受胁迫', sourceDocumentId: 'doc-zhao', provenance: { kind: 'investigation', sourceId: 'investigate-zhao-family' }, tags: ['motive'] },
    { id: 'claim-lu-ledger-change', text: '陆淳修改粮册', sourceDocumentId: 'doc-du', provenance: { kind: 'document', sourceId: 'doc-du' }, tags: ['supports'] },
  ],
  investigations: [
    { id: 'investigate-zhao-family', title: '查询赵简家人', cost: 1, revealClaimIds: ['claim-zhao-coerced'] },
  ],
  interrogations: [
    {
      id: 'interrogate-zhao-time',
      characterId: 'zhao',
      statementClaimId: 'claim-zhao-denial',
      evidenceClaimId: 'claim-zhao-copied-order',
      revealClaimIds: ['claim-zhao-time'],
      responseKeys: {
        calm: 'zhao.calm',
        threaten: 'zhao.threaten',
        empathize: 'zhao.empathize',
        misdirect: 'zhao.misdirect',
      },
    },
  ],
  baits: [
    { id: 'bait-lu-south', channel: 'lu', payload: '南线驿马', signal: 'southDispatch', requiredClaimIds: [], core: false },
    { id: 'bait-zheng-36', channel: 'zheng', payload: '三十六辆', signal: '36', requiredClaimIds: [], core: false },
    { id: 'bait-zhao-yin', channel: 'zhao', payload: '寅时', signal: 'yin', requiredClaimIds: ['claim-zhao-time'], core: true },
    { id: 'bait-du-north-bridge', channel: 'du', payload: '北桥', signal: 'northBridge', requiredClaimIds: ['claim-du-route', 'claim-bridge-open'], core: true },
  ],
  relationshipPermissions: [
    { fromId: 'claim-zhao-time', toId: 'zhao', kind: 'accessedBy', slot: 'actor' },
    { fromId: 'claim-du-route', toId: 'du', kind: 'infers', slot: 'method' },
    { fromId: 'du', toId: 'claim-shuoyuan-received', kind: 'transmitsTo', slot: 'enemyConclusion' },
    { fromId: 'claim-zhao-copied-order', toId: 'claim-zhao-denial', kind: 'refutes', slot: 'leakedInfo' },
    { fromId: 'claim-zhao-copied-order', toId: 'zhao', kind: 'accessedBy', slot: 'actor' },
  ],
  hints: { timeSource: ['方向', '文书', '矛盾'] },
  epilogueFragments: {
    'outcome.networkClosed': '封网成功。',
    'outcome.convoySavedIncomplete': '保粮失人。',
    'outcome.ambushedAgain': '再次伏击。',
    'owner.canghe': '真相交给曹军。',
    'owner.shuoyuan': '真相交给袁军。',
    'owner.lishe': '真相交给官渡里社。',
    'owner.destroyed': '关键证据被销毁。',
    'lu.canghe': '陆淳受审。',
    'lu.shuoyuan': '陆淳离开驿站。',
    'lu.lishe': '陆淳受里社保护。',
    'lu.destroyed': '陆淳的秘密未被公开。',
    'zheng.accused': '郑禾被错误牵连。',
    'zheng.cleared': '郑禾洗清通敌嫌疑。',
    'zhao.coerced': '赵简的胁迫事实得到确认。',
    'zhao.traitor': '赵简被作为叛徒处置。',
    'du.identified': '杜衡的暗号渠道被识破。',
    'du.escaped': '杜衡带着渠道秘密逃脱。',
    'player.canghe': '玩家留在曹军控制下。',
    'player.shuoyuan': '玩家选择袁军。',
    'player.lishe': '玩家站在官渡里社一边。',
    'player.destroyed': '玩家独自保守真相。',
  },
};
